/**
 * Created by Akshat on 05-09-2017.
 */


export const LOGIN_EMAIL_CHANGED = 'LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_INPUT_CHANGE = 'REGISTER_INPUT_CHANGE';
export const SIGNUP_INIT = 'SIGNUP_INIT';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SENDING_PASSWORD_REQUEST = 'SENDING_PASSWORD_REQUEST';
export const REQUEST_PASSWORD_FAIL = 'REQUEST_PASSWORD_FAIL';
export const REQUEST_PASSWORD_SUCCESS = 'REQUEST_PASSWORD_SUCCESS';